# Generated by Django 3.1.1 on 2021-03-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='password',
        ),
        migrations.AddField(
            model_name='school',
            name='mode',
            field=models.BooleanField(default=False),
        ),
    ]
